#! /bin/sh

# Autostart
sxhkd &
feh --bg-scale "/home/labibmahmud/.config/Wallpapers/yourname.png" &
polybar -c /home/labibmahmud/.config/polybar/config mybar -r &
picom --animations -b &

# For Arch based distros
exec /usr/lib/xfce4/notifyd/xfce4-notifyd &

# Regular monitor output
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

### WINDOW CONFIG ###
bspc config border_width         2 
bspc config top_padding          28 
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#928374
bspc config focused_border_color \#d79921

### APPLICATION RULES ###
# Example: bspc rule -a Gimp desktop='^8' state=floating follow=on
