#! /bin/sh

# Autostart
sxhkd &
feh --bg-scale "/home/labibmahmud/.config/Wallpapers/nihonYoru1.jpg" &
# feh --bg-scale "/home/labibmahmud/.config/Wallpapers/Bleach.jpg" &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
# exec /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &

# Sets dual monitors, change HDMI1 to your according output
# xrandr --output eDP-1 --auto --output HDMI-1 --left-of eDP-1 &

# Set second monitor as primary monitor, change HDMI1 to your according output
# xrandr --output eDP1 --off --output HDMI1 --auto &

# Regular monitor output
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

# To split the number of workspaces between the two displays, uncomment the two lines below.
# bspc monitor HDMI-1 -d 1 2 3 4 5
# bspc monitor eDP-1 -d 6 7 8 9 10

# When setting HDMI display as primary display, uncomment the line below.
# bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10 

### WINDOW CONFIG ###
bspc config border_width         2 
bspc config top_padding          24 
bspc config window_gap           5
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#0b0c17
bspc config focused_border_color \#74c8ef

### APPLICATION RULES ###
# Example: bspc rule -a Gimp desktop='^8' state=floating follow=on
